
  CREATE TABLE "ROLE" 
   (	"ROLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ROLE_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ROLE_PK" PRIMARY KEY ("ROLE")
   ) ;

   COMMENT ON COLUMN "ROLE"."ROLE" IS 'ÉçÅ[ÉãID';
   COMMENT ON COLUMN "ROLE"."ROLE_NAME" IS 'ÉçÅ[Éãñº';

