
  CREATE TABLE "MENU_CATEGORY" 
   (	"MENU_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "MENU_CATEGORY_PK1" PRIMARY KEY ("MENU_ID", "CATEGORY"), 
 	 CONSTRAINT "MENU_CATEGORY_FK1" FOREIGN KEY ("MENU_ID") REFERENCES "MENU" ("MENU_ID") ENABLE, 
	 CONSTRAINT "MENU_CATEGORY_FK2" FOREIGN KEY ("CATEGORY") REFERENCES "CATEGORY" ("CATEGORY") ENABLE
   ) ;

   COMMENT ON COLUMN "MENU_CATEGORY"."MENU_ID" IS 'メニューID';
   COMMENT ON COLUMN "MENU_CATEGORY"."CATEGORY" IS 'カテゴリID';

