  CREATE TABLE "CATEGORY" 
   (	"CATEGORY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CATEGORY_NAME" VARCHAR2(50 BYTE), 
	"POSITION" NUMBER(3,0), 
	"CATEGORY_PID" VARCHAR2(20 BYTE), 
	 CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATEGORY")
   );

   COMMENT ON COLUMN "CATEGORY"."CATEGORY" IS 'カテゴリID';
   COMMENT ON COLUMN "CATEGORY"."CATEGORY_NAME" IS 'カテゴリ名';
   COMMENT ON COLUMN "CATEGORY"."POSITION" IS '表示位置';
   COMMENT ON COLUMN "CATEGORY"."CATEGORY_PID" IS '親カテゴリ';