
  CREATE TABLE "USERS" 
   (	"USER_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(20 BYTE), 
	"LAST_LOGIN_DATE" TIMESTAMP (0), 
	"DEL_FLG" VARCHAR2(1 BYTE), 
	"CREATE_DATE" TIMESTAMP (0) NOT NULL ENABLE, 
	"CREATE_USER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"UPDATE_DATE" TIMESTAMP (0) NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID"), 
	 CONSTRAINT "USERS_FK1" FOREIGN KEY ("ROLE") REFERENCES "ROLE" ("ROLE") ENABLE
   ) ;

   COMMENT ON COLUMN "USERS"."USER_ID" IS 'ユーザーID';
   COMMENT ON COLUMN "USERS"."USER_NAME" IS 'ユーザー名';
   COMMENT ON COLUMN "USERS"."PASSWORD" IS 'パスワード';
   COMMENT ON COLUMN "USERS"."EMAIL" IS 'メールアドレス';
   COMMENT ON COLUMN "USERS"."ROLE" IS 'ロール';
   COMMENT ON COLUMN "USERS"."LAST_LOGIN_DATE" IS '最終ログイン日時';
   COMMENT ON COLUMN "USERS"."DEL_FLG" IS '削除FLG';
   COMMENT ON COLUMN "USERS"."CREATE_DATE" IS '作成日時';
   COMMENT ON COLUMN "USERS"."CREATE_USER" IS '作成者';
   COMMENT ON COLUMN "USERS"."UPDATE_DATE" IS '更新日時';
   COMMENT ON COLUMN "USERS"."UPDATE_USER" IS '更新者';

